#!/bin/sh

SOURCES="
main.cpp
option_spec.cpp
serial_pricer.cpp
opencl_pricer.cpp"

FRAMEWORK="-framework OPENCL"

TARGET="-o main.tsk"

CXX="clang++"

VERSION="-std=c++11"

$CXX $FRAMEWORK $VERSION $SOURCES $TARGET
